### ISSUE TITLE
Having problems running script...

### ISSUE THREAD

**Issue by ghost** [amnuts/jwplayer-thumbnail-preview-generator#2]
Hey there,

Thanks for writing this php script to generate thumbnails - just what I was looking for... However, I have yet to successfully run the script on my mp4 files. I always get following error:

"Could not find any thumbnails matching '/Users/user/Desktop/WIP/thumbnails/sweeny_todd_act_01-\d{4}.jpg'"

I am using following command:

php thumbnails.php -i "/Users/user/Desktop/WIP/Sweeny_Todd_Act_01.mp4" -v -t 60 -w 120

and no thumbnails are created:( Could you point me into the right direction...

Thanks,
- Uwe Willenbacher

**Comment by amnuts** [comment]
Hi,

I suspect that your ffmpeg install is not liking the command to generate thumbnails, which is why the CallbackFilter is not producing any results and the script is exiting. You could try showing the output from the command (if any).  On line 126 echo out the `shell_exec(sprintf($commands['thumbs']...` part and see if it tells you anything.

Do you know what version of ffmpeg you're using?

Andy

**Comment by amnuts** [comment]
@uwew I came across some issues today that may have been causing the script to fail to find thumbnails even if it had created them.  This wasn't a problem on Windows but I did see it on Ubuntu.  Give the latest commit a try and see if that fixes the problem for you.  If not, let me know if you're having any luck with my previous comment.
