### ISSUE TITLE
Problem to run

### ISSUE THREAD

**Issue by amnweb** [amnuts/jwplayer-thumbnail-preview-generator#5]
Why i have error
`PHP Parse error:  syntax error, unexpected '[' in /home/public_html/thumbnails.php on line 15`

i'm run this command 
`php thumbnails.php -i "y402169.mp4"`

**Comment by amnuts** [comment]
The code uses the short array syntax (`[]` instead of `array()`) which was introduced as of version 5.4.  If you're getting that error then it would indicate that the version of PHP that you're using is older than 5.4.

If you don't have the option of updating your version of PHP (which hopefully you do because there have been many great advances!) then just alter the code to use the full array syntax.  That would essentially be the `$params` array _starting on line 15_, the `$commands` array _starting on line 24_ and the default array setting on _line 96_.

**Comment by amnweb** [comment]
Yes i just make edits of file now i have another error hmm...
`PHP Fatal error:  Class 'CallbackFilterIterator' not found in /home/public_html/thumbnails.php on line 132`

**Comment by amnuts** [comment]
Ah, yes.  The CallbackFilterIterator is also a PHP 5.4+ class.  You can apply the code found on http://php.net/manual/en/class.callbackfilteriterator.php (first comment) to replicate the CallbackFilterIterator class.
